= Board game

Digital remake of an old-school board game. The original game was issued in Hungary and was in Hungarian.
With help of some enthusiasts we might recreate even reimagine an age-old classic.

== Installation
All installation needs to be done with pip3!
Any Directory you import data from needs to include an __init__.py file, in order to be accessible when started over the
OS.

== Goals
This is by default a turn based merchant strategy game for a number of players btw. 2 - 6.
All rulez will first be implemented, as shown in the original manual.
With no clear goals - other than having fun - we might reach some of the following milestones during development.

- adding graphics
- hotseat multiplayer style
- parallel multiplayer style
- multi-computer playing mode (LAN)
- browser based playing style
- game rebalancing
- additional game features
- multi language support

== Contribution
Any help is welcome. In some areas it is of advantage if you know, or even have a copy of the original game.
However most of the rule and gamesetup related issues are either already implemented or easy to communicate.

== Packages
I'll try to keep this repo as simple as possible, with no external deps, as long as possible.

== Run
We'll simply have a desktop icon for basic testruns.
Once development reaches multiplayer level, we'll probably convert it into a browser game.

== Owner
Sziller
